Feature/edit and remove custom task
Sundsvallskommun/web-app-boarding pull request #18
Opened 2024-12-02 13:03 UTC by aliceringstromsk

## Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] Removed feature
- [ ] Code style update (formatting etc.)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Content/Data

## Does this PR introduce a breaking change?
- [ ] Yes (I have stepped the version number accordingly)
- [x] No
      
## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (if applicable).
- [ ] I have added/updated tests to cover my changes (if applicable).

2024-12-02 15:19 UTC, jerkerosatiesk requested changes
Flytta felmeddelanden till språkfiler.
Annars bra.

2024-12-02 15:19 UTC, jerkerosatiesk commented on frontend/src/components/edit-task-modal/edit-task-modal.component.tsx
> +  heading: yup.string().min(1, 'Du måste skriva en rubrik').required('Du måste skriva en rubrik'),
Flytta felmeddelande till språkfil.

2024-12-02 15:20 UTC, jerkerosatiesk commented on frontend/src/components/activity-list-item/activity-list-item.component.tsx
> +                            Redigera
Språkfiler?

Redigera och Ta bort är sådana saker som kan ligga i "common"

2024-12-03 14:43 UTC, jerkerosatiesk approved these changes

2024-12-03 14:48 UTC, timlindsk approved these changes

2024-12-03 14:49 UTC, merged