Feature/delegations and mentor
Sundsvallskommun/web-app-boarding pull request #22
Opened 2024-12-11 09:08 UTC by aliceringstromsk

## Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] Removed feature
- [ ] Code style update (formatting etc.)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Content/Data

## Does this PR introduce a breaking change?
- [ ] Yes (I have stepped the version number accordingly)
- [x] No
      
## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (if applicable).
- [ ] I have added/updated tests to cover my changes (if applicable).

2024-12-11 15:03 UTC, jerkerosatiesk requested changes

2024-12-11 15:03 UTC, jerkerosatiesk commented on frontend/src/pages/[userId]/index.tsx
> +  const data =
Får felmeddelande när datat ska loopas.
`Cannot read properties of undefined (reading 'map')`

2024-12-11 15:17 UTC, jerkerosatiesk commented on frontend/src/components/assign-mentor-modal/assign-mentor-modal.component.tsx
> +            Lägg till mentor
Språkfil?

2024-12-11 15:20 UTC, jerkerosatiesk commented on frontend/src/components/checklist-sidebar/checklist-sidebar.component.tsx
> +                        <Button
Knappen ser ej rätt ut?
tertiary med showbackground=false?

2024-12-12 13:02 UTC, jerkerosatiesk approved these changes
Om name-attributen fyller någon funktion så är det ok

2024-12-12 13:13 UTC, hensankom approved these changes

2024-12-12 13:14 UTC, merged